#!/bin/bash
#
# pre-commit hook: run pep8 and pylint

ALL_FILES=$( git diff --cached --name-status \
                 | grep -v ^D | awk '$1 $2 { print $2}' \
                 | grep -E -- '-cleaner$|.py$' )

if [ -z "$ALL_FILES" ]; then
    exit 0
fi

pep8 --config pep8.conf  $ALL_FILES || {
    echo "pep8 failed. Fix code or use --no-verify."
    exit 1
}

pylint --rcfile=pylint.conf -f text $ALL_FILES > pylint.log || {
    echo "Pylint failed, log in pylint.log."
    echo "Fix code or use --no-verify."
    exit 3
}
exit 0
