#!/usr/bin/env python
'''
Support poor admin when trying to keep config files up-to-date.

Synopsis:
    etc-cleaner

Searches  for updated configuration files in /etc with versions
created by package updates. User sees a list of changes and can
remove unneeded files, merge changes with e. g., backup versions
or just accept changes done.

There are no commandline options.
'''
# pylint: disable=W0611,E0611

import os.path
import sys

PATH = os.path.dirname(os.path.realpath(sys.argv[0]))
PYTHONPATH = PATH
# These are patched by installation scripts.

try:
    from gi.repository import Gtk
    Gtk.init(sys.argv)
except RuntimeError as e:
    print ("etc-cleaner: "  + str(e))
    print ("This is a graphical application and requires DISPLAY to be set.")
    sys.exit(1)

sys.path.insert(0, PYTHONPATH)
sys.path.insert(0, os.path.join(PYTHONPATH, 'etc-cleaner'))

if not PATH in os.environ['PATH']:
    os.environ['PATH'] = PATH + ':' + os.environ['PATH']

from etc_cleaner import etc_cleaner

# vim: set expandtab ts=4 sw=4:
