#!/bin/bash
#
# zenity wrapper used as sudo askpass helper

# http://forums.gentoo.org/viewtopic-t-947210-start-0.html
export NO_AT_BRIDGE=0

zenity --password --title="$*" || {
    pgroup=$(ps -ho pgid $$)
    sudo kill -TERM -${pgroup/ /}
}
